### ISSUE TITLE
`petablox.dynamic.timeout` not working with `petablox.reflect.kind` = "external".

### ISSUE THREAD

**Issue by kalhauge** [petablox-project/petablox#18]
Petablox external and dynamic does not receive the petablox.dynamic.timeout options. 

Steps to reproduce:

1. Download and build https://github.com/ucla-pls/baseline
2. Run petablox using these settings:
```
petablox.datalog.engine=bddbddb
petablox.main.class=edu.ucla.pls.baseline.Infinite
petablox.run.analyses=cipa-0cfa-dlog,reachable-methods
petablox.err.file=/dev/stderr
petablox.out.file=/dev/stdout
petablox.jvmargs=-Xmx40960m
petablox.runtime.jvmargs=-Xmx40960m
petablox.class.path=baseline/build/classes
petablox.reflect.kind=external
petablox.dynamic.timeout=10
petablox.run.ids=default
petablox.args.default=
```
3. Then the `external` analysis does not end in 10 seconds. 

Note: Doing the same thing with `dynamic` have the same problem:

```
petablox.datalog.engine=bddbddb
petablox.main.class=edu.ucla.pls.baseline.Infinite
petablox.run.analyses=cipa-0cfa-dlog,reachable-methods
petablox.err.file=/dev/stderr
petablox.out.file=/dev/stdout
petablox.jvmargs=-Xmx40960m
petablox.runtime.jvmargs=-Xmx40960m
petablox.class.path=baseline/build/classes
petablox.reflect.kind=dynamic
petablox.dynamic.timeout=10
petablox.run.ids=default
petablox.args.default=
```

**Comment by kalhauge** [comment]
@XujieSi, 

Turned out that I was to fast about the dynamic reflection analysis. It does not work either. I was thinking that a `petablox.reflection.timeout` option would be a good idea, and then use that instead
of the `petablox.dynamic.timeout` option.

Do you think this is possible?

**Comment by kalhauge** [comment]
@XujieSi 

I tried your newest changes in master (9b9d391b2863fc948b6ea0bb5b01133af0ad8b7a), 
but it did not work. The following program does not terminate:

```
petablox.datalog.engine=bddbddb
petablox.main.class=edu.ucla.pls.baseline.Infinite
petablox.run.analyses=reachable-methods
petablox.err.file=/dev/stderr
petablox.out.file=/dev/stdout
petablox.jvmargs=-Xmx40960m
petablox.runtime.jvmargs=-Xmx40960m
petablox.class.path=/nix/store/y2cqqaz2ghpd5dl4rwzri90ab337zx86-baseline/share/java/baseline.jar
petablox.reflect.kind=dynamic
petablox.reflection.timeout=5
petablox.reflection.haltonerr=false
petablox.run.ids=default
petablox.args.default=
```

Also maybe we should rename 'reflection' to 'reflect', so that they match each other.

**Comment by XujieSi** [comment]
@kalhauge 
Did you try it on the baseline?  
I tested it on your baseline, which is fine. The setting I have used:
` petablox.datalog.engine=bddbddb
 petablox.main.class=edu.ucla.pls.baseline.Infinite
 petablox.run.analyses=cipa-0cfa-dlog,reachable-methods
 petablox.err.file=/dev/stderr
 petablox.out.file=/dev/stdout
 petablox.jvmargs=-Xmx40960m
 petablox.runtime.jvmargs=-Xmx40960m
 petablox.class.path=build/classes
 petablox.reflect.kind=external
 #petablox.reflect.kind=dynamic
 #petablox.dynamic.timeout=10000
 petablox.reflection.timeout=10000
 petablox.run.ids=default
 petablox.args.default=`

**Comment by kalhauge** [comment]
Ah ! It seams like it is working for "external", but not for "dynamic".

**Comment by XujieSi** [comment]
Yes, I think so.
dynamic reflection is an instance of dynamic analysis, `petablox.dynamic.timeout` will affect dynamic analysis in general.

**Comment by kalhauge** [comment]
Okay, so the reflection.timeout only affect the external reflection handler. Shouldn't it then be called `petablox.external.timeout` instead?
