### ISSUE TITLE
Petablox hangs after completed execution

### ISSUE THREAD

**Issue by kalhauge** [petablox-project/petablox#19]
Using jdk 1.6 or 1.8, when executing petablox hangs for an indefinite time after 
execution is complete.  Weirdly enough does it not hang when run with version 1.7.

Test setup here: https://www.dropbox.com/sh/jozka2k9wgbjf5e/AADN63xI9Zctjd1ONOJ7N7iWa?dl=0

Final lines of output:
```
Finished command: 'java -ea -Xmx1024m -cp /nix/store/fqm4k4z4lrzgma3qqyi19hahz9ld1zdn-petablox/share/java/petablox.jar: -Dverbose=1 -Dbdd=j -Dbasedir=/net/nauru/one/home/kalhauge/projects/jbx/test/bug/petablox_output/bddbddb net.sf.bddbddb.Solver /net/nauru/one/home/kalhauge/projects/jbx/test/bug/petablox_output/dlog/petablox_analyses_alias_cipa_0cfa.dlog '
LEAVE: cipa-0cfa-dlog
Exclusive time: 00:00:31:056 hh:mm:ss:ms
Inclusive time: 00:02:11:520 hh:mm:ss:ms
LEAVE: cicg-java
Exclusive time: 00:00:00:000 hh:mm:ss:ms
Inclusive time: 00:02:11:520 hh:mm:ss:ms
LEAVE: reachable-methods
Exclusive time: 00:02:11:619 hh:mm:ss:ms
Inclusive time: 00:02:11:619 hh:mm:ss:ms
Petablox run completed at: Apr 18, 2017 1:18:44 PM
Total time: 00:02:20:067 hh:mm:ss:ms
```
And then it hangs.

The version of petablox we use is "858145766780994393596824f74d49a33a575da7" from 
master.

**Comment by XujieSi** [comment]
@kalhauge This patch https://github.com/petablox-project/petablox/commit/7a9f5c761ee6718a4f9f6577c74ab5fa78a759ca should resolve this issue. Let me know if it is not the case.

**Comment by kalhauge** [comment]
It is working now :), thanks :)
